apiVersion: v1
kind: Service
metadata:
  name: coding-ui-service
  labels:
    app: coding
    tier: ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  selector:
    app: coding
    tier: ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coding-api-ingress
spec:
  rules:
  - host: coding.tsa.local.webstorm.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coding-ui-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coding
      tier: ui
  template:
    metadata:
      labels:
        app: coding
        tier: ui
    spec:
      containers:
      - name: coding-ui
        image: ghcr.io/tj-cappelletti/tsa/submissions/coding/ui:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: ui-http-svc
