authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
      enabled: true

server:
  ingress:
    ingressClassName: webapprouting.kubernetes.azure.com
    enabled: true
    hosts:
      - auth.webstorm.cloud

    tls:
      - hosts:
          - auth.webstorm.cloud
        secretName: authentik-cert-secret

postgresql:
    enabled: true

redis:
    enabled: true