authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
      enabled: true

server:
  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - auth.tsa.local

    # tls:
    #   - hosts:
    #       - auth.webstorm.cloud
    #     secretName: authentik-cert-secret

postgresql:
    enabled: true

redis:
    enabled: true