apiVersion: v1
kind: Service
metadata:
  name: coding-mongodb-service
  labels:
    app: coding
    tier: db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: coding
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-mongodb
spec:
  selector:
    matchLabels:
      app: coding
      tier: db
  template:
    metadata:
      labels:
        app: coding
        tier: db
    spec:
      containers:
        - name: coding-mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: coding-configmap
                  key: submissions.database.username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coding-secret
                  key: password
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
