apiVersion: v1
kind: Service
metadata:
  name: coding-api-service
  labels:
    app: coding
    tier: api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
  selector:
    app: coding
    tier: api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coding-api-ingress
spec:
  rules:
  - host: tsa.webstorm.cloud
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: coding-api-service
            port:
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coding
      tier: api
  template:
    metadata:
      labels:
        app: coding
        tier: api
    spec:
      containers:
      - name: coding-api
        image: ghcr.io/tj-cappelletti/tsa/submissions/coding/webapi:latest
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__Redis
          value: "coding-cache-service:6379"
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: jwt.audience
        - name: Jwt__ExpirationInHours
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: jwt.expirationInHours
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: jwt.issuer
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: coding-secrets
              key: jwt.key
        - name: Jwt__RequireHttpsMetadata
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: jwt.requireHttpsMetadata
        - name: SubmissionsDatabase__Host
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: database.submissions.host
        - name: SubmissionsDatabase__LoginDatabase
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: database.submissions.loginDatabase
        - name: SubmissionsDatabase__Name
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: database.submissions.name
        - name: SubmissionsDatabase__Password
          valueFrom:
            secretKeyRef:
              name: coding-secrets
              key: database.submissions.password
        - name: SubmissionsDatabase__Port
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: database.submissions.port
        - name: SubmissionsDatabase__UserName
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: database.submissions.username
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: api-http-svc
        livenessProbe:
          httpGet:
            path: /api/status
            port: api-http-svc
        readinessProbe:
          httpGet:
            path: /api/status
            port: api-http-svc
          initialDelaySeconds: 5
          timeoutSeconds: 15
