apiVersion: v1
kind: Service
metadata:
  name: coding-api-service
  labels:
    app: coding
    tier: api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
  selector:
    app: coding
    tier: api
# This is to assign a static IP
# This will need to be changed for production use
#status:
#  loadBalancer:
#    ingress:
#    - ip: 172.16.0.55
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coding
      tier: api
  template:
    metadata:
      labels:
        app: coding
        tier: api
    spec:
      containers:
      - name: coding-api
        image: ghcr.io/tj-cappelletti/tsa/submissions/coding/webapi:latest
        env:
        - name: SubmissionsDatabase__Name
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: submissions.database.name
        - name: SubmissionsDatabase__Host
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: submissions.database.host
        - name: SubmissionsDatabase__Port
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: submissions.database.port
        - name: SubmissionsDatabase__UserName
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: submissions.database.username
        - name: SubmissionsDatabase__Password
          valueFrom:
            secretKeyRef:
              name: coding-secret
              key: password
        - name: SubmissionsDatabase__LoginDatabase
          valueFrom:
            configMapKeyRef:
              name: coding-configmap
              key: submissions.database.loginDatabase
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: api-http-svc
        livenessProbe:
          httpGet:
            path: /api/status
            port: api-http-svc
        readinessProbe:
          httpGet:
            path: /api/status
            port: api-http-svc
          initialDelaySeconds: 5
          timeoutSeconds: 15
