apiVersion: v1
kind: ConfigMap
metadata:
  name: coding-configmap
  labels:
    app: coding
data:
  database.submissions.host: coding-mongodb-service
  database.submissions.loginDatabase: admin
  database.submissions.name: submissions
  database.submissions.port: '27017'
  database.submissions.username: root
