apiVersion: v1
kind: ConfigMap
metadata:
  name: coding-configmap
  labels:
    app: coding
data:
  submissions.database.host: coding-mongodb-service
  submissions.database.loginDatabase: admin
  submissions.database.name: submissions
  submissions.database.port: '27017'
  submissions.database.username: root
