apiVersion: v1
kind: Service
metadata:
  name: coding-mongodb-service
  namespace: coding
  labels:
    app: coding
    tier: db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: coding
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-mongodb
  namespace: coding
spec:
  selector:
    matchLabels:
      app: coding
      tier: db
  template:
    metadata:
      labels:
        app: coding
        tier: db
    spec:
      containers:
        - name: coding-mongodb
          image: mongo:latest
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: coding-configmap
                  key: database.submissions.username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coding-secrets
                  key: database.submissions.password
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: coding-mongodb-pvc
